//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Homon {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsCust : DataSet {
        
        private CustomerListDataTable tableCustomerList;
        
        public dsCust() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsCust(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["CustomerList"] != null)) {
                    this.Tables.Add(new CustomerListDataTable(ds.Tables["CustomerList"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CustomerListDataTable CustomerList {
            get {
                return this.tableCustomerList;
            }
        }
        
        public override DataSet Clone() {
            dsCust cln = ((dsCust)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["CustomerList"] != null)) {
                this.Tables.Add(new CustomerListDataTable(ds.Tables["CustomerList"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableCustomerList = ((CustomerListDataTable)(this.Tables["CustomerList"]));
            if ((this.tableCustomerList != null)) {
                this.tableCustomerList.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsCust";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsCust.xsd";
            this.Locale = new System.Globalization.CultureInfo("zh-CN");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableCustomerList = new CustomerListDataTable();
            this.Tables.Add(this.tableCustomerList);
        }
        
        private bool ShouldSerializeCustomerList() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void CustomerListRowChangeEventHandler(object sender, CustomerListRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CustomerListDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnCustomerBirth;
            
            private DataColumn columnCustomerName;
            
            internal CustomerListDataTable() : 
                    base("CustomerList") {
                this.InitClass();
            }
            
            internal CustomerListDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn CustomerBirthColumn {
                get {
                    return this.columnCustomerBirth;
                }
            }
            
            internal DataColumn CustomerNameColumn {
                get {
                    return this.columnCustomerName;
                }
            }
            
            public CustomerListRow this[int index] {
                get {
                    return ((CustomerListRow)(this.Rows[index]));
                }
            }
            
            public event CustomerListRowChangeEventHandler CustomerListRowChanged;
            
            public event CustomerListRowChangeEventHandler CustomerListRowChanging;
            
            public event CustomerListRowChangeEventHandler CustomerListRowDeleted;
            
            public event CustomerListRowChangeEventHandler CustomerListRowDeleting;
            
            public void AddCustomerListRow(CustomerListRow row) {
                this.Rows.Add(row);
            }
            
            public CustomerListRow AddCustomerListRow(System.DateTime CustomerBirth, string CustomerName) {
                CustomerListRow rowCustomerListRow = ((CustomerListRow)(this.NewRow()));
                rowCustomerListRow.ItemArray = new object[] {
                        CustomerBirth,
                        CustomerName};
                this.Rows.Add(rowCustomerListRow);
                return rowCustomerListRow;
            }
            
            public CustomerListRow FindByCustomerName(string CustomerName) {
                return ((CustomerListRow)(this.Rows.Find(new object[] {
                            CustomerName})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                CustomerListDataTable cln = ((CustomerListDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new CustomerListDataTable();
            }
            
            internal void InitVars() {
                this.columnCustomerBirth = this.Columns["CustomerBirth"];
                this.columnCustomerName = this.Columns["CustomerName"];
            }
            
            private void InitClass() {
                this.columnCustomerBirth = new DataColumn("CustomerBirth", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCustomerBirth);
                this.columnCustomerName = new DataColumn("CustomerName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCustomerName);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnCustomerName}, true));
                this.columnCustomerName.AllowDBNull = false;
                this.columnCustomerName.Unique = true;
            }
            
            public CustomerListRow NewCustomerListRow() {
                return ((CustomerListRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new CustomerListRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(CustomerListRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CustomerListRowChanged != null)) {
                    this.CustomerListRowChanged(this, new CustomerListRowChangeEvent(((CustomerListRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CustomerListRowChanging != null)) {
                    this.CustomerListRowChanging(this, new CustomerListRowChangeEvent(((CustomerListRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CustomerListRowDeleted != null)) {
                    this.CustomerListRowDeleted(this, new CustomerListRowChangeEvent(((CustomerListRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CustomerListRowDeleting != null)) {
                    this.CustomerListRowDeleting(this, new CustomerListRowChangeEvent(((CustomerListRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveCustomerListRow(CustomerListRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CustomerListRow : DataRow {
            
            private CustomerListDataTable tableCustomerList;
            
            internal CustomerListRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableCustomerList = ((CustomerListDataTable)(this.Table));
            }
            
            public System.DateTime CustomerBirth {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableCustomerList.CustomerBirthColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableCustomerList.CustomerBirthColumn] = value;
                }
            }
            
            public string CustomerName {
                get {
                    return ((string)(this[this.tableCustomerList.CustomerNameColumn]));
                }
                set {
                    this[this.tableCustomerList.CustomerNameColumn] = value;
                }
            }
            
            public bool IsCustomerBirthNull() {
                return this.IsNull(this.tableCustomerList.CustomerBirthColumn);
            }
            
            public void SetCustomerBirthNull() {
                this[this.tableCustomerList.CustomerBirthColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CustomerListRowChangeEvent : EventArgs {
            
            private CustomerListRow eventRow;
            
            private DataRowAction eventAction;
            
            public CustomerListRowChangeEvent(CustomerListRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public CustomerListRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
